### ISSUE TITLE
Realización de backups

### ISSUE THREAD

**Issue by danhidsan** [danhidsan/decide-ganimedes-almacenamiento#1]
Implementar en el sub-sistema de almacenamiento mediante la cual sea posible hacer un backup de todas las votaciones que se encuentran almacenadas en en la base de datos. 

Esto se implementará directamente en sistema de administración que tiene Django por defecto. En la misma interfaz de la votaciones donde se realiza el comienzo, la parada y el recuento de las votaciones, debemos implementar otra funcionalidad mediante la que sea posible realizar un backup de una o varias votaciones.

El backup de dichas votaciones podría hacerse por ejemplo en uno o varios archivos .csv. Aunque se aceptan otras propuestas de tipo de backup.

**Comment by joaquinperez94** [comment]
Habría que ver que tipo de backup se va a realizar, si completo de todo el esquema de toda la base de datos o solo de ciertas tablas.
Una vez decidido eso ya podría ir definiendo el tipo de query para  exportar la base de datos.

**Comment by danhidsan** [comment]
En principio habrá que implementar las siguientes peticiones a la base de datos, con el fin de obtener un fichero con un backup de dichas peticiones:
1. Datos de una votación, es decir, habrá qué hacer una petición a la base de datos en la que obtengamos todos los datos de una votación. Habrá que obtener todos los datos de qué estén relacionados con la tabla de una votación.
2. Datos de varias o todas las votaciones, es decir, habrá que obtener todos los datos de varias o todas las votaciones.

@joaquinperez94
