### ISSUE TITLE
¿Qué otra nueva funcionalidad podríamos desarrollar?

### ISSUE THREAD

**Issue by julgargal** [danhidsan/decide-ganimedes-almacenamiento#15]
Debido a que las funcionalidades propuestas en el Milestone 1 ya han sido desarrolladas o están en proceso de desarrollo, ¿Se os ocurre qué nueva funcionalidad podríamos añadir?

**Comment by joaquinperez94** [comment]
@danhidsan Pregúntale al equipo encargado del panel de control si necesitarían una nueva llamada a la API, en la que se le pase por parámetro el id de un votante y nos devuelva las votaciones en las que ha votado.
Podría ser una nueva funcionalidad interesante para el panel de control.

**Comment by danhidsan** [comment]
Esta incidencia estaba creada a modo de pregunta para los integrantes del grupo de trabajo. Actualmente ya no es necesaria. Se cierra la incidencia.
