### ISSUE TITLE
Estructura y organización de la rama notificacion_votacion

### ISSUE THREAD

**Issue by marjimveg1** [danhidsan/decide-ganimedes-almacenamiento#16]
Se ha creado una rama "notificacion_votacion" a partir de la rama master con el fin de implementar la funcionalidad de notificar cuando se registar una votación. 

Quienes vayan a trabajar en esta rama crearán otra rama aparte con el nombre "notificacion_votacion_nombre". Cuando tenga realizada su implementación realizará un merge a la rama "notificacion_votacion".

De esta forma cada miembro puede trabajar paralelamente en la funcionalidad sin crear conflicto dentro de la rama  general.

Una vez esté finalizada la implementación de la funcionalidad se realizará un pull request de la rama "notificacion_votacion" a la rama master.

**Comment by joaquinperez94** [comment]
@danhidsan Pregúntale al equipo encargado del panel de control si necesitarían una nueva llamada a la API, en la que se le pase por parámetro el id de un votante y nos devuelva las votaciones en las que ha votado. 
Podría ser una nueva funcionalidad interesante para el panel de control.

**Comment by danhidsan** [comment]
@julgargal @marjimveg1 Esto no es buena idea, ya que a la persona que le toqué revisar la nueva funcionalidad, va a tener que perder tiempo resolviendo los conflictos que se puedan ocasionar separando la funcionalidad en 2 ramas. Os recomiendo que creéis una sola rama a partir de master, y que trabajéis las dos en la misma rama.

**Comment by danhidsan** [comment]
Se cierra esta incidencia debido a que es meramente informativa. No aporta nada a la funcionalidad del sistema.
