### ISSUE TITLE
Implementación con MongoDB (NoSQL)

### ISSUE THREAD

**Issue by joaquinperez94** [danhidsan/decide-ganimedes-almacenamiento#19]
Para cubrir la embergadura del proyecto se nos ha aconsejado la implementación de MongoDB en nuestro sistema, pero para que no afecté a la integración con los demás grupos, dicha implementación no deberá de sustituir a la base de datos usada actualmente (postgreSQL), sino que podremos elegir en el sistema la estructura de base de datos a usar.

Para esta issue será necesario el estudio de la base de datos actualmente y cómo se almacenan los datos para pasarlos a lenguaje NoSQL. Habrá que cambiar la clase models.py que es donde se define la estructura de la base de datos en django.

**Comment by danhidsan** [comment]
¿En qué estado se encuentra esta nueva mejora? @joaquinperez94

**Comment by joaquinperez94** [comment]
Estoy teniendo muchos problemas con las compatibilidades de las versiones entre Django-mongodb-engine  y Python hasta el punto que vía stackoverflow he descubierto que mongodb-engine no es compatible con python3 y por tanto hay que buscar una nueva alternativa. Adjunto url del hilo donde se dice que no es compatible:

[https://stackoverflow.com/questions/34256041/error-while-setting-up-mongodb-with-django-using-django-mongodb-engine-on-window](url)

En teoría está correctamente configurado pero al no ser compatible con python3 me salta el siguiente error:

`  File "/home/joaquin/Documentos/Proyecto/decide-ganimedes-almacenamiento/decide/decide-ganimedes-almacenamiento/local/lib/python3.6/site-packages/django_mongodb_engine/base.py", line 272
    raise ImproperlyConfigured, exc_info[1], exc_info[2]
                              ^
SyntaxError: invalid syntax
`

Estoy estudiando una nueva alternativa para implementar mongoDB como puede ser djongo.
@danhidsan

**Comment by joaquinperez94** [comment]
Se ha creado una nueva rama llamada "mongoDB_djongo" en la que se está implementando la base de datos MongoDB en el proyecto decide  a partir de djongo.
Actualmente mongoDB se encuentra funcionando correctamente para lo distintos módulos.(Se ha comprobado mediante la herramienta Robo 3T que se insertan registros correctamente en la base de datos mongoDB).
Quedaría implementar la funcionalidad de que decide trabaje por defecto con PostgreSQL en todos los módulos menos en el módulo de store que implementaría MongoDB.
Dicha funcionalidad ya estoy estudiándola y hay que aplicar unos routers para redireccionar las bases de datos.
También hay que tener en cuenta que al hacer el comando migrate sólo migra una base de datos y por tanto deberíamos de ejecutar:
`python3 manage.py migrate database=nombre_bd_mongo`

**Comment by joaquinperez94** [comment]
### **DE PASOS QUE HE SEGUIDO PARA CONFIGURAR MONGODB CON DJONGO**

**1.** Instalamos mongodb descargandolo desde la página oficial:
    [https://www.mongodb.com/download-center/community](url)

Una vez instalado podemos comprobar que este correctamente funcionando con el comando:
    `systemctl status mongodb`

-Debería de salirnos por pantalla:
```
● mongodb.service - An object/document-oriented database
   Loaded: loaded (/lib/systemd/system/mongodb.service; enabled; vendor preset: enabled)
   Active: active (running) since Fri 2018-12-28 15:31:35 WET; 1h 21min ago
     Docs: man:mongod(1)
 Main PID: 1234 (mongod)
    Tasks: 35 (limit: 4915)
   CGroup: /system.slice/mongodb.service
           └─1234 /usr/bin/mongod --unixSocketPrefix=/run/mongodb --config /etc/mongodb.conf
dic 28 15:31:35 joaquin-SATELLITE-L850-1RZ systemd[1]: Started An object/document-oriented database.

```
-Para comprobar el puerto donde está ejecutándose mongo:
   `mongo --eval 'db.runCommand({ connectionStatus: 1 })'`


**2.** Instalamos djongo
   `pip install djongo`

**3.** En settings.py sustituimos la base de datos por defecto (postgreSQL) por djongo:
```
    'default': {
        'ENGINE': 'djongo',
        'NAME': 'mongodb',
    }
```

**4.** En local_settings.py sustituimos la base de datos por defecto por:
```
     'default':{
        'ENGINE' : 'djongo',
        'NAME': 'mongodb',
        'HOST': 'localhost',
        'PORT': 27017,
    }
```

**5.** Realizamos la migración de la base datos:
```
    python3 manage.py makemigrations
    python3 manage.py migrate
```

**6.** Creamos un usuario para poder logearnos en el panel admin de Django.
  `  python3 manage.py createsuperuser`

**7.** Por último probamos que podemos crear usuarios,votaciones, etc desde el panel de administración de django y que se insertan correctamente en la base de datos.
Para visualizar la base de datos mongoDB he usado Robo 3T.

**Comment by danhidsan** [comment]
He leído los comentarios y parece que la implementación de MongoDB esta bastante bien encaminada. Con respecto a lo de crear una ruta para que solo guarde en MongoDB los datos de almacenamiento de votos, ¿Cómo va esa parte de la tarea?

**Comment by joaquinperez94** [comment]
Aún implementando el router para redirigir la base de datos se store hacía mongo no consigo que funcione independientemente de la base de datos de postgreSQL.
Sigo intentando su integración.

**Comment by joaquinperez94** [comment]
@danhidsan **ACTUALIZO**
Sigo teniendo problemas con la implementación de las 2 bases de datos, aunque estén declaradas ambas sólo detecta una y por tanto sólo funciona con una misma base de datos a la vez.
El sistema funciona correctamente ya sea con MongoDB o PostgreSQL aunque no los dos a la vez.

**Comment by joaquinperez94** [comment]
Con respecto a esta issue se ha hablado con el profesor para informarle de su progreso para que nos diera feedback y se ha llegado a las siguientes conclusiones:
-Dejar, al menos por el momento, la implementación de ambas base de datos mediante el uso de routers.
-Testear el sistema funcionando con mongoDB, comprobando que todas las entidades se crean correctamente y se guardan en la base de datos mongoDB.
-Editar el fichero docker-settings.py para usar mongoDB. Como ayuda el profesor nos ha aconsejado mirar la documentación en: [https://hub.docker.com/_/mongo](url)

**Comment by joaquinperez94** [comment]
@danhidsan 
Al encontrar tantos errores a muy bajo nivel, he decido implementar mongoDB sólo en el modulo **store**, quedando los demás módulos funcionando con postgreSQL.
Para ello he conseguido implementar el router que hace que para el módulo store envíe todas las llamadas de base de datos a la base de datos en mongoDB.

Para hacer su configuración es necesario realizar como hasta ahora:
`python manage.py makemigrations` 
`python manage.py migrate`

Pero además tendremos que ejecutar el siguiente comando que hará la migración del modulo store en la base de datos mongoDB.
`python manage.py migrate --database=nombre_BD_en_mongo`

**Comment by joaquinperez94** [comment]
Adjunto capturas de pantalla en las que se puede observar como los votos quedan guardados en la base de datos de mongoDB y, los usuarios por ejemplo, pertenecientes al módulo de autenticación son guardados en la base de datos de postgreSQL. Ambas bases de datos funcionando simultáneamente.

### Votos son guardaos en MongoDB:
![image](https://user-images.githubusercontent.com/32302020/50838504-0bf17700-1356-11e9-9b80-55673dc319b9.png)

### Uusarios son guardados en PostgreSQL:
![image](https://user-images.githubusercontent.com/32302020/50838723-9df97f80-1356-11e9-9c16-32c867f8a819.png)

**Comment by joaquinperez94** [comment]
@danhidsan Hay que ver que al implementar mongoDB sólo en el módulo store se podrá subir el settings.py tal cual o dejarlo como está.
Hay que decidirlo para realizar el pull request y subirlo a master de nuestro repo para luego integrarnos con los demás.

**Comment by danhidsan** [comment]
@joaquinperez94 crea el pull request para que así pueda ver los cambios que has hecho y lo comentamos en los comentarios del mismo.

**Comment by danhidsan** [comment]
Funcionalidad terminada. Se cierra la incidencia.
