### ISSUE TITLE
Hacer posible el almacenamiento de varios votos

### ISSUE THREAD

**Issue by danhidsan** [danhidsan/decide-ganimedes-almacenamiento#20]
Desde el sub-sistema de cabina se nos ha comunicado que es necesario poder almacenar mas de un voto. Habrá que modificar la parte en la que se almacenan los votos de forma que sea posible almacenar un voto o una lista de votos. 

[Incidencia del repositorio padre](https://github.com/decide-ganimedes/decide-ganimedes/issues/18)

**Comment by danhidsan** [comment]
Me encargo yo de esta incidencia. @joaquinperez94 @marjimveg1 @julgargal

**Comment by marjimveg1** [comment]
@danhidsan no dijimos que íbamos a hacerlo @julgargal o yo?

**Comment by danhidsan** [comment]
@marjimveg1 @julgargal  Por mi perfecto. Pero he estado hablando con el sub-sistema de cabina, y esta funcionalidad debe de estar lista para este fin de semana. ¿Cómo lo veis?

**Comment by marjimveg1** [comment]
No sabia que habían puesto fecha límite, creía que solo había sido una propuesta por parte de cabina. Tenerlo para mañana es imposible por mi parte, necesitaría un par de días.

**Comment by danhidsan** [comment]
@marjimveg1 La fecha límite es debido a que la funcionalidad de votación múltiple depende de varios cambios en todo el sistema decide, faltaría los cambios en almacenamiento y en visualización, por lo tanto para que esa funcionalidad este completa y funcione debe de estar el paso mas importante, que es almacenar los votos

**Comment by marjimveg1** [comment]
De acuerdo, me encargo yo.

**Comment by danhidsan** [comment]
Se ha concluido la funcionalidad.
