### ISSUE TITLE
Test para segunda llamada API

### ISSUE THREAD

**Issue by joaquinperez94** [danhidsan/decide-ganimedes-almacenamiento#26]
Revisando los test de travis se nos ha pasado la implementación del test de la segunda llamada de la API que se implementó.
Se trata de realizar el test para la llamada a la API en la que le pasas el id de un votante y te devolvía todas las votaciones en las que ese usuario ha votado.

**Comment by danhidsan** [comment]
@joaquinperez94 ¿En qué estado se encuentra esta incidencia?

**Comment by joaquinperez94** [comment]
Está en proceso pero debido a los continuos errores que estoy teniendo con el mergeo e integración de la rama de mongoDB con todos los sistemas la he tenido que dejar a un lado.

**Comment by joaquinperez94** [comment]
@danhidsan Test implementado, no se ha creado una nueva rama ni se ha pedido pull request al ser un modificación pequeña y tener prioridad urgente.
En este [commit](https://github.com/danhidsan/decide-ganimedes-almacenamiento/commit/48d68775c8e8886157d3c1263eab2050adf77259) se puede ver el código y su implementación.

**Comment by danhidsan** [comment]
Se ha comprobado que los test a implementar funcionan correctamente y la release y el sistema están desplegados. Se cierra la incidencia.
