### ISSUE TITLE
Implementar un panel de control general de las votaciones

### ISSUE THREAD

**Issue by danhidsan** [danhidsan/decide-ganimedes-almacenamiento#3]
Para la elaboración de un panel de control, tendremos que realizar las consultas necesarias en almacenamiento de votos para después mostrarlas en la interfaz de usuario.

En principio desde el modulo de almacenamiento de votos, no será necesario crear una parte "Frontend" de la incidencia, ya que en principio los encargados de esto serán los integrantes del sub-sistema de visualización.

Esta incidencia está enlazada con la siguiente incidencia del repositorio general:
[Estadísticas en tiempo de votación](https://github.com/decide-ganimedes/decide-ganimedes/issues/5)

**Comment by danhidsan** [comment]
En principio desde el módulo de visualización, que es el que se encarga de mostrar los datos del panel de control, nos ha pedido que implementemos lo siguiente:
- En principio es necesario implementar en la API una ruta que devuelva una lista con todos los votates de una votación

**Comment by joaquinperez94** [comment]
En principio no se puede saber los votantes de una votación, sólo se puede ver cuántos han votado en cada votación.

Edito: Me auto respondo, cogiendo los ids sí podemos sacarlos.

**Comment by danhidsan** [comment]
¿Podríamos dar por cerrada esta incidencia no? @joaquinperez94

**Comment by joaquinperez94** [comment]
@danhidsan sí, se puede dar por cerrada a falta de hacer los test.

**Comment by danhidsan** [comment]
Se da por cerrada esta incidencia. La nueva funcionalidad se encuentra tanto en nuestro fork como en el repositorio padre.
