### ISSUE TITLE
El usuario no debería poder votar mas de una vez en una votación

### ISSUE THREAD

**Issue by danhidsan** [danhidsan/decide-ganimedes-almacenamiento#9]
Actualmente en la plataforma de votación de Decide, es posible votar con el mismo usuario mas de una vez en la misma votación. 

Esto no debería ser posible, por lo que hay que implementar en la llamada de votación la forma de controlar que no se pueda votar más de una vez en una misma votación.

**Comment by joaquinperez94** [comment]
Con respecto a esta issue, sí es verdad que puede votar más de una vez, pero no se almacenan los votos 2 veces, sino que se queda almacenado el último.

**Comment by danhidsan** [comment]
Efectivamente, se puede votar más de una vez pero los voto se almacenan 2 veces, por lo que esta incidencia quedaría cerrada.
